# Generated by Django 5.2.8 on 2025-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_familygroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
