# Generated by Django 5.2.8 on 2025-11-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_profile_nickname_alter_familygroup_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.familygroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
