# Generated by Django 5.2.8 on 2025-11-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_profile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
    ]
