# Generated by Django 5.2.8 on 2025-11-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_remove_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
